name: ops Tests

on: [push, pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Install tox
        run: pip install tox

      - name: Run linting
        run: tox -e lint

  static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Install tox
        run: pip install tox

      - name: Run static type checks
        run: tox -e static

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.10"]
        root: [true, false]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox globally
        run: sudo pip install tox

      - name: Run unit tests
        if: ${{ !matrix.root }}
        run: tox -e unit

      - name: Run unit tests as root
        if: ${{ matrix.root }}
        run: sudo tox -e unit

  test-real-pebble:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: "1.17"

      - name: Install tox
        run: pip install tox

      - name: Install Pebble
        run: go install github.com/canonical/pebble/cmd/pebble@latest

      - name: Start Pebble
        run: |
          umask 0
          $HOME/go/bin/pebble run --create-dirs --http=:4000 &
        env:
          PEBBLE: /tmp/pebble

      - name: Run Real pebble tests
        run: tox -e unit -- -k RealPebble
        env:
          RUN_REAL_PEBBLE_TESTS: 1 
          PEBBLE: /tmp/pebble

  pip-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Build
        run: python setup.py sdist

      # Test that a pip install of the source dist .tar.gz will work
      - name: Test 'pip install'
        # Shouldn't happen, but pip install will fail if ls returns multiple lines
        run: pip install $(ls dist/ops*.gz)
